---
- name: FABRIC BUILD
  hosts: all
  gather_facts: no

  vars:
    nxos_ssh:
      host: "{{ ansible_host }}"
      username: "{{ user }}"
      password: "{{ pw }}"
      transport: cli

  tasks:
    - name: "Set lo0"
      nxos_interface:
        provider: "{{ nxos_ssh }}"
        name: Loopback 0
        state: present

    - name: "Set lo0 ip"
      nxos_l3_interface:
        provider: "{{ nxos_ssh }}"
        name: Loopback 0
        ipv4: "{{ hostvars[inventory_hostname]['lo0_ipaddr'] }}/32"
        state: present

    - name: "Set ethernet ports to jumbo"
      nxos_interface:
        provider: "{{ nxos_ssh }}"
        name: "ethernet 1/{{item}}"
        state: present
        mode: layer3
        mtu: 9216
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Set ethernet ports to p2p and unnumbered"
      nxos_config:
        provider: "{{ nxos_ssh }}"
        lines:
          - medium p2p
          - ip unnumbered lo0
        before:
          - "interface ethernet 1/{{item}}"
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Enable OSPF feature"
      nxos_feature:
        provider: "{{ nxos_ssh }}"
        feature: ospf
        state: enabled

    - name: "Create OSPF router instance"
      nxos_ospf:
        provider: "{{ nxos_ssh }}"
        ospf: 1
        state: present

    - name: "Enable interface OSPF (eth)"
      nxos_interface_ospf:
        provider: "{{ nxos_ssh }}"
        interface: "ethernet 1/{{item}}"
        ospf: 1
        area: 0
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Enable interface OSPF (lo0)"
      nxos_interface_ospf:
        provider: "{{ nxos_ssh }}"
        interface: lo0
        ospf: 1
        area: 0
